export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_LOGGEDIN_USER = "SET_LOGGEDIN_USER";
export const LOGOUT = "LOGOUT";
export const GET_USER_DATA = "GET_USER_DATA";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE"